import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import AppProviders from "@/components/AppProviders";

const publicSans = Public_Sans({
  variable: "--ff-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} antialiased`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
